# Generated by Django 4.2 on 2023-10-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='uesr',
            new_name='user',
        ),
    ]
